### ISSUE TITLE
Stop taking over bash syntax.

### ISSUE THREAD

**Issue by envygeeks** [atom/language-csharp#102]
As the title says. For some reason when there is `#!/bin/bash -l` you assume it's a nant build file.

**Comment by HebaruSan** [comment]
I'm seeing this for a bash script called `build`, I think because of this:

https://github.com/atom/language-csharp/blob/364ba38ee2e9abcd219bfc7684f206f29715d894/grammars/build.cson#L3-L5

**Comment by envygeeks** [comment]
That too! Yeah every time I open up my `script/build` 😢

**Comment by damieng** [comment]
Any thoughts on this @shiftkey ?  Not sure what to replace the mapping with to make it msbuild specific.

**Comment by HebaruSan** [comment]
I wanted to try changing it to `fileTypes: [ "\\.build" ]` to see if that would still work for real NAnt files, but I couldn't find the grammar file in Atom. Is it installed in compressed form on Windows?

**Comment by 50Wliu** [comment]
Yes.  To get around that you can clone the repository and then `apm link --dev` it, then run Atom in developer mode (`atom --dev`).

**Comment by HebaruSan** [comment]
Thanks. Nope, my idea did not work; with both `"\\.build"` and just `".build"`, it failed to recognize NAnt.Console.build as a NAnt build file, and defaulted to normal XML.

**Comment by damieng** [comment]
I'm thinking the best option here might be to just drop NAnt files from the language-csharp grammar.  It's not a core part of the C# tooling and it could be easily provided by a 3rd party for those that need it.

**Comment by HebaruSan** [comment]
That solution would work well for me, but I don't know how well I fit the profile of your target audience for this package. I don't use NAnt and had to go looking for a sample file for testing.

**Comment by damieng** [comment]
I've used .NET since 1.0 and have never used NAnt... it looks like their last release was 5 years ago.

**Comment by shiftkey** [comment]
Belated :thumbsup: to removing the NAnt support, especially if it wasn't implemented properly and meddled with other file extensions :fire:
