### ISSUE TITLE
Add support for C# 7.2 keyword contexts

### ISSUE THREAD

**Issue by anurse** [atom/language-csharp#112]
C# 7.2 added a number of new "keywords" (mostly just new places existing keywords can be used). These don't show up properly in GitHub colorization (see below) and the path of submodules led me here

See https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-2 for reference.

Examples:

```csharp
// 'readonly' should be colorized like 'struct'
public readonly struct Foo
{
}

// 'ref' should be colorized like 'struct'
public ref struct Foo
{
}

// 'ref' should be colorized
public static ref Bar GetBar()
{
}

// 'in' works
// 'ref readonly' works
// 'private protected' works
```

**Comment by damieng** [comment]
Hey Andrew.

We've actually switched language-csharp over to an official Microsoft supplied grammar that has support for these alas github.com has not been able to upgrade to it yet as it uses some extensions the github highlighter does not support (named groups). 

We're looking at whether we can manually or automatically change the grammar here so it can still work for github.com

**Comment by worldbeater** [comment]
Hello, Damien!

Could you please provide more info with examples describing what an unsupported named group is and how it should be replaced in order to support GitHub highlighters? Perhaps, the community and I can do all the routine work or write a script that will parse and fix all that stuff for you!

We love C# and we love GitHub, but we are quite disappointed with how current highlighter works. So we'll be glad to provide you any help we can 😸

**Comment by damieng** [comment]
@worldbeater I'm also disappointed (C# is my fave language). Our options right now are:

1. Go back to the old parser and try and improve it in parallel with Microsoft's efforts. This was tricky in the past as the textmate grammar syntax is an unwieldy beast anyway.  We'd probably want to fork this repo from the old one so Atom can keep using the Microsoft effort and we'd switch linguist over.

2. Figure out some kind of conversion between this and PCRE.  I've tried doing this by hand and got nowhere fast.  I suspect the older version of PCRE that GitHub supports might be missing the features we need entirely given my attempts.

3. Switch GitHub's linguist grammar for C# over to a textmate grammar - if somebody is maintaining one still.

4. Hold out for changes to linguist to support different syntax engines such as Oniguruma or tree-sitter.

**Comment by worldbeater** [comment]
Holding out for changes in GitHub internals [can take time](https://github.com/github/linguist/issues/3291#issuecomment-379448471), so we can start working on existing C# TextMate bundle improvements. Some fixes already are [here](https://github.com/atom/language-csharp/pull/109) and [here](https://github.com/atom/language-csharp/pull/108), other ones are not so difficult to implement.

**Comment by Alhadis** [comment]
Careful pattern order, intelligent structure, and a little judicious repetition can all achieve the same effect as a named-group or a subroutine call. I've never needed these features in my grammars, ever.

I recently started work on a [replacement](https://github.com/Alhadis/language-js) JavaScript grammar for GitHub, which includes support for JSX and static Flow typing. I've barely spent must time on it and it's already showing improvement:

* [Before](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.js&grammar_format=auto&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FAlhadis%2Flanguage-js%2F7b5e140489efb73bf8dac6cac5e8c2b44cdfdea9%2Ftests%2Fimports.es5&code=)
* [After](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FAlhadis%2Flanguage-js%2F7b5e140489efb73bf8dac6cac5e8c2b44cdfdea9%2Fgrammars%2Fjs.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FAlhadis%2Flanguage-js%2F7b5e140489efb73bf8dac6cac5e8c2b44cdfdea9%2Ftests%2Fimports.es5&code=)

You'll see that what most users deem impossible without Oniguruma extensions are, in fact, possible without *any* extensions.

**Comment by Alhadis** [comment]
> Figure out some kind of conversion between this and PCRE. I've tried doing this by hand and got nowhere fast. I suspect the older version of PCRE that GitHub supports might be missing the features we need entirely given my attempts.

@damieng Could you point to an example where these features were used? I don't know a single thing about C#, so I'm in the dark when it comes to how bad its highlighting is on GitHub...

**Comment by damieng** [comment]
I'm not saying that they're not possible without extensions - I'm saying that in order for us to switch to the official Microsoft-maintained C# grammar we'd need Oniguruma support or a reliable conversion.  

I think if GitHub wants to continue to tap the grammars used in clients this is going to be more and more of a problem if they use those features.

Do you know what version of PCRE is available?  The features being used appear to be named captures but my attempt at conversion was not successful when I tested it.

**Comment by worldbeater** [comment]
@damieng please check https://github.com/github/linguist/issues/3291#issuecomment-381115027 (thanks a lot to John Gardner for providing info!) Perhaps, numbered groups instead of named groups can be used if `(?&name)` groups are not working?

**Comment by damieng** [comment]
Yeah I converted the whole grammar file by hand using that approach and it
made no difference at least on the limited testing tool I have available.

**Comment by worldbeater** [comment]
@damieng we finally managed to get Microsoft's grammar work with GitHub. Here is a pull request with a working demo on [Github Lightshow Heroku App](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fworldbeater%2Flanguage-csharp%2Faf991b07b724c7f42a4fde9800143d31fb68c7fc%2Fgrammars%2Fcsharp.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2Fworldbeater%2Fc7cb51a1f6b07d5b8a46d3df5983d047%2Fraw%2F918acf82490816ea8d9a36f0bb9dccee8c2e6c97%2FFeedbackFormViewModel.cs&code=). https://github.com/atom/language-csharp/pull/116

Hope our assistance could help GitHub continue being the best service for hosting open-source projects! 😹

**Comment by damieng** [comment]
This should now work fine in Atom - it will be some time however before github.com picks up the latest. I'll see what we can do to get that expedited.
