### ISSUE TITLE
Incorrect syntax highlighting when method name has prefix and argument has /*

### ISSUE THREAD

**Issue by kasper3** [atom/language-csharp#113]
Incorrect syntax highlighting:

```c#
A.Call("/*");
AfterCall();
```

Distilled:

![image](https://user-images.githubusercontent.com/33230602/36992281-1af722e0-20b3-11e8-8cbf-c135d85a1ca9.png)

Correct by removing `A.`:

```c#
Call("/*");
AfterCall();
```

**Comment by damieng** [comment]
Is this in Atom?  Or for github.com ?

**Comment by damieng** [comment]
It is but GitHub.com is using an older version of the grammar.  We're working on figuring out how to ship the new grammar on github.com - it uses some features not available there right now. Stay tuned!

**Comment by kasper3** [comment]
> Stay tuned!

Anything i can do to help/speed up fixing the blocking issues? Where to send PR, what to fix etc. while my radio is tuned. :)

**Comment by damieng** [comment]
Unfortunately the new grammar (in this repo) uses a lot of Oniguruma specific extensions while github.com is tied to a fork of PCRE that doesn't support them.

**Comment by kasper3** [comment]
@damieng, thanks. I read somewhere to post C# syntax related issues to this repo, instead of GitHub/linguist. In this situation, do you think we should move this to linguist or other PCRE-based repo? Or should we try to hook up this to GitHub.com?

**Comment by damieng** [comment]
I summarize our options here https://github.com/atom/language-csharp/issues/112#issuecomment-379094384

**Comment by damieng** [comment]
This should be picked up by github.com next time they pull our grammar :)
