### ISSUE TITLE
Incorrect LINQ Syntax Highlighting

### ISSUE THREAD

**Issue by rvhuang** [atom/language-csharp#114]
I have [a piece of example code](https://github.com/rvhuang/linq-to-astar#example) in my repository which mainly contains LINQ statements. However, `where`, `orderby` and `select` clauses are all not highlighted correctly.

![image](https://user-images.githubusercontent.com/11286168/38539269-4144515c-3c4c-11e8-8470-0abe2bf18dc0.png)

Aside from LINQ, normal static function call (`Console.WriteLine`) is also not highlighted. Please help.

**Comment by damieng** [comment]
Is this in Atom (if so which version) or on github.com ?

**Comment by worldbeater** [comment]
Github ofc
```csharp
var queryable = from step in astar.Except(GetObstacles())
                where step.X >= 0 && step.Y >= 0 && step.X <= 40 && step.Y <= 40
                orderby step.GetManhattanDistance(goal)
                select step;
```

**Comment by damieng** [comment]
github.com isn't using the language-c# grammar that is in this repo right now - we upgraded to a much newer system that isn't compatible with the mechanism behind github.com.

**Comment by rvhuang** [comment]
@damieng thanks for the information. Is it possible to forward the issue to GitHub?

**Comment by damieng** [comment]
It looks like both Atom and GitHub can now use the grammar thanks to @worldbeater  :)
