### ISSUE TITLE
#endif isn't treated as a preprocessor token

### ISSUE THREAD

**Issue by moswald** [atom/language-csharp#20]
```csharp
#if DEBUG
#endif
```

These are detected as:

#if - span.meta.preprocessor.source.cs
DEBUG - span.entity.name.function.preprocessor.source.cs
#endif - span.meta.method.body.source.cs

**Comment by pchaigno** [comment]
I think we need to rewrite the whole [preprocessor section](https://github.com/atom/language-csharp/blob/master/grammars/c%23.cson#L455-L475).
I have never used preprocessor directives in C#. Is it the exact same as in C/C++?

**Comment by moswald** [comment]
It's not the _exact_ same. There's not really a "preprocess" step taken by the C# compiler, but the end result is the same for conditional compilation. Macros are not possible.

That said, any of the keywords that start with `#` is a preprocessor keyword.
