### ISSUE TITLE
Incorrect string highlight for parameter attributes

### ISSUE THREAD

**Issue by Measuring** [atom/language-csharp#22]
![image](https://cloud.githubusercontent.com/assets/1107063/6204183/f889ca76-b541-11e4-87e6-5a03e656e9f9.png)

Beginning " is not matched.

**Comment by 50Wliu** [comment]
Refs #15.

**Comment by Measuring** [comment]
Refs #13.

**Comment by 50Wliu** [comment]
Inlining text for convenience:
```cs
namespace Test
{
    public class Test
    {
        public void Execute([BotDisplay(Description = "Command to execute on the server.")] string command)
        {
            // Wrongly highlighted.
        }
    }
}
```

Minimal repro case:
```cs
public class Test
{
    public void a([b(c = "Command s")] string q)
    {
        // Wrongly highlighted.
    }
}
```

**Comment by pchaigno** [comment]
Looks like the minimal repro case might be even worse:
```cs
class Poller {
  A a = b("c");
}
```
(Reported by @Tanjoodo at github/linguist#2661.)

**Comment by 50Wliu** [comment]
@pchaigno Can you test out #39 and see if that fixes your issue?

**Comment by Tanjoodo** [comment]
As far as I can tell, in the Atom editor, everything looks right. 

I cloned this repo, `apm link`ed got, #39 as a .diff file and `git apply 39.diff`ed. Then I opened this file: https://github.com/Tanjoodo/autoproxy/blob/master/AutoProxy/Poller.cs and it was highlighted correctly. I also tried the minimal repro cases provided by @pchaigno and they both worked.

I wrote in such detail so you could verify that I tested it correctly.

**Comment by pchaigno** [comment]
It looks [good in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fatom%2Flanguage-csharp%2Fwl-prioritize-strings%2Fgrammars%2Fc%2523.cson&grammar_text=&code_source=from-text&code_url=&code=public+class+Test%0D%0A%7B%0D%0A++++b%28%22Command+s%22%29%3B+%2F%2F+bug%0D%0A%7D%0D%0Apublic+class+Test%0D%0A%7B%0D%0A++++b%28%22Commands%22%29%3B+%2F%2F+no+bug%0D%0A%7D) too :-)
The `b` is not highlighted anymore though, is that normal?

**Comment by Tanjoodo** [comment]
I'm going to assume not because the patch assumes the method regex was overeager.
