### ISSUE TITLE
Incorrect highlighting for interpolated strings (Roslyn)

### ISSUE THREAD

**Issue by stefan-baumann** [atom/language-csharp#23]
Interpolated strings (a new Roslyn feature) are not highlighted correctly. Example:
![atom string interpolation highlighting](https://cloud.githubusercontent.com/assets/4400519/6325913/75c14162-bb4c-11e4-9957-e6077a6c8be8.png)

**Comment by shiftkey** [comment]
Should the closing `}` also be highlighted?

**Comment by stefan-baumann** [comment]
I'd do it like this:
The opening and closing sequences (`\{` and `}`) should either be as normal text or like a part of the string. The sequence inside the curly brackets should be highlighted like normal C#-code.

**Comment by patriksvensson** [comment]
Interpolated strings should start with a `$`, so I don't think the code stated above is correct anymore.

https://msdn.microsoft.com/en-us/library/dn961160.aspx

**Comment by 50Wliu** [comment]
@stefan-baumann can you confirm that this isn't valid syntax anymore?

**Comment by khellang** [comment]
@50Wliu This is old syntax. The new syntax is `$"It measures {distance:0.00}m"`. See "String interpolation" under https://github.com/dotnet/roslyn/wiki/Languages-features-in-C%23-6-and-VB-14.

**Comment by khellang** [comment]
Interpolated strings are still an issue, though. See #43.

**Comment by 50Wliu** [comment]
Ok, since the original example is no longer valid, I'm closing this out.
