### ISSUE TITLE
This package is listed as a community package rather than core

### ISSUE THREAD

**Issue by exalted** [atom/language-csharp#26]
Any ideas?

**Comment by shiftkey** [comment]
I believe this is right - core packages are the ones which are included in-the-box with Atom, and everything else is considered a community package.

Am I missing something?

**Comment by willl** [comment]
I think PR #5408 (https://github.com/atom/atom/pull/5408) added language-csharp to the core.

**Comment by exalted** [comment]
@shiftkey I was actually thinking more that, since this package is under https://github.com/atom, it should've been core. Not sure.

**Comment by shiftkey** [comment]
@willl ah yes, I missed that PR. thanks for the extra context.

Just checked the latest version of Atom and it seems to be listed as a core package:

![screen shot 2015-03-05 at 9 03 32 am](https://cloud.githubusercontent.com/assets/359239/6495061/8e64d7d4-c316-11e4-91b7-adcc67c234fd.png)

@exalted can you clarify where it's being listed as a package incorrectly? Maybe it's an old version of the package that needs to be updated?

**Comment by thedaniel** [comment]
I am guessing this is because you had it installed from atom.io already before it was added to core. I wonder, is it ALSO listed under core?

**Comment by exalted** [comment]
@shiftkey sorry for the delay, anyhow, this is what I see right now:

![settings_-_atom](https://cloud.githubusercontent.com/assets/314398/6578722/1c95f0dc-c746-11e4-84eb-ecfec327323a.jpg)

**Comment by kevinsawicki** [comment]
You might want to check if `language-csharp` is installed to `~/.atom` and remove it if it is there so that the bundled version is always used instead of the installed version.

Closing this out.

**Comment by exalted** [comment]
:+1:
