### ISSUE TITLE
Incorrect hightlighting for "HTTP/1.1"

### ISSUE THREAD

**Issue by metadings** [atom/language-csharp#28]
Please have a look on [Microsoft.AspNet.Server.Kestrel](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L353).

**Comment by pchaigno** [comment]
@metadings Could you update your link (and [make it permanent](https://help.github.com/articles/getting-permanent-links-to-files/))? You can also post an example here directly with the syntax:
    
    ```cs
    [your code]
    ```

**Comment by 50Wliu** [comment]
@pchaigno I assume the issue is in this line since syntax highlighting is broken after that:
https://github.com/aspnet/KestrelHttpServer/blob/ca0a42a01e5b46e98b2b84588685b444790aaa50/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L353

**Comment by pchaigno** [comment]
@50Wliu Thanks!
I can also reproduce with a simple snippet (without the `class`, it works fine):
```cs
public class Frame : FrameContext, IFrameControl {
  private static readonly ArraySegment<byte> _continueBytes = CreateAsciiByteArraySegment("HTTP/1.1 100 Continue\r\n\r\n");
}
```
I'll investigate!
