### ISSUE TITLE
Indentation update mistake

### ISSUE THREAD

**Issue by NDavidBrown** [atom/language-csharp#31]
I have my tab indentation set to 2 spaces.

Let's say I have this code:

```
public void foo() {
  var myVar = null;
}
```

If I add a line above it, when I hit semicolon the indentation jumps for both the initial and the new line

```
# About to hit semicolon
public void foo() {
  this.doStuff() # <- caret is after the bracket here
  var myVar= null;
}

# Just hit semicolon
public void foo() {
        this.doStuff(); # Just typed this semicolon
        var myVar = null;
}
```

As well as the indentation messing up, the caret jumps to an awful position several chars before `var myvar`.

**Comment by thomasjo** [comment]
Are you able to reproduce this in safe mode? `atom --safe`
I'm reasonably sure this is caused by a community package.

**Comment by NDavidBrown** [comment]
You're right - it doesn't occur with `--safe`. Thanks.

**Comment by 50Wliu** [comment]
In that case, you can either try to manually disable packages until you find out which one is causing it, or use @mark-hahn's [package-cop](https://atom.io/packages/package-cop) package.

**Comment by NDavidBrown** [comment]
@50Wliu  Thank you for the suggestion and link, I'll try package-cop :grinning:
