### ISSUE TITLE
Comments break highlighting of variable declaration in classes

### ISSUE THREAD

**Issue by Cu3PO42** [atom/language-csharp#32]
As you can see `public byte AltFormCount` is highlighted correctly, wheres `public byte FormPointer` is not. This appears to be related to the comment, since it will be highlighted correctly when the comment is removed.

It is also noteworthy that this problem only occurs inside class definitions, but not inside methods.

![screen shot 2015-08-13 at 18 16 43](https://cloud.githubusercontent.com/assets/5256300/9255185/065a4a8a-41e8-11e5-8a5b-3fcdcab17058.png)

**Comment by pchaigno** [comment]
I can't reproduce the issue (GitHub uses this grammar to highlight C# code):
```cs
public class Customer {
  public byte AltFormCount;
  public byte FormPointer; // 720 + FormPointer
}
```
I also tried with the last version of Atom.
Am I missing something?

**Comment by Cu3PO42** [comment]
The issue persists for me. The code is [https://github.com/kwsch/PKHeX/blob/master/Misc/PKX.cs#L1672-L1673](here).

**Comment by 50Wliu** [comment]
@Cu3PO42 Thanks.  This gets very interesting, watch closely:
```c#
//Everything works
struct hi
{
    byte q;  //Hey look a comment
}

//No comments and also no +/- signs
struct hi
{
    byte q;  // 721  FormPointer  (FormID  1) = SpeciesIndex
}

//Original example
struct hi
{
    byte q;  // 721 + FormPointer + (FormID - 1) = SpeciesIndex
}

//Minimal repro for the original issue (notice the opening parentheses - that's what's causing the problem)
struct hi
{
    byte q; //(
}
```

Looks like the comment support has some pretty subtle bugs.

**Comment by Cu3PO42** [comment]
I must say this bug is only one-upped by a single one I encountered while writing the TypeScript grammar. I'm sure this will be "fun" to debug.
