### ISSUE TITLE
Unnecessary `source` scopes

### ISSUE THREAD

**Issue by MaximSokolov** [atom/language-csharp#35]
In other languages there is no `source` scopes for languages symbols. I guess it might cause problems if packages would use scopes.

![image](https://cloud.githubusercontent.com/assets/2943616/9505370/afe69b32-4c4a-11e5-87b3-c8d7b0f336d9.png)

**Comment by pchaigno** [comment]
@MaximSokolov Do you want to open a pull request to remove them?

**Comment by MaximSokolov** [comment]
@pchaigno It would be great if you fix it.
