### ISSUE TITLE
[C#] colorizer - syntax highlighting error when curly brace in a comment after an assignment

### ISSUE THREAD

**Issue by aeschli** [atom/language-csharp#42]
_From @glennc on November 25, 2015 23:9_

With the following code:

```c#
var a = 0; // {
```
the `// {` isn't green like the other comments.

_Copied from original issue: Microsoft/vscode#675_

**Comment by aeschli** [comment]
For C# tokenization we use the text mate grammar from https://github.com/atom/language-csharp.
I verified that Atom has the same issue, so it's really a grammar issue (and not problem with our text mate engine).
I suggest to file the issue there as well.

**Comment by 50Wliu** [comment]
I can't reproduce this using language-csharp v0.11.0:
![image](https://cloud.githubusercontent.com/assets/2766036/11483582/16d34dbe-9777-11e5-9d77-0fc8e4914176.png)

@aeschli what version is Code using?

**Comment by aeschli** [comment]
Hm, sorry, I realize that my test example was not valid code. With valid code all colorizes correctly.
I will have to ask the user for a full code example.
Sorry for that and thanks for the help.
