### ISSUE TITLE
[C#] syntax coloring breaks down with interpolated strings

### ISSUE THREAD

**Issue by aeschli** [atom/language-csharp#43]
_From @jumpinjackie on December 2, 2015 6:40_

Using VSCode 0.10.3

The C# syntax coloring breaks down when interpolated strings are involved.

Example code

``` c#
    namespace Test
    {
        public class Foo
        {
            static string AddTableName(string suffix) => $"Bar{suffix}_ADD";

            static string ModTableName(string suffix) => $"Bar{suffix}_MOD";

            static string DelTableName(string suffix) => $"Bar{suffix}_DEL";
        } 
    }
```

VSCode screenshot

![capture](https://cloud.githubusercontent.com/assets/563860/11524059/965e200e-991b-11e5-869b-2ec886350ee0.png)

_Copied from original issue: Microsoft/vscode#900_

**Comment by aeschli** [comment]
Same problem in Atom (language-csharp v0.11.0):
![image](https://cloud.githubusercontent.com/assets/6461412/11533509/65f3c7d6-990a-11e5-9201-769cf3241325.png)

**Comment by 50Wliu** [comment]
I plan on looking at these in the coming weeks, provided my schedule works out.  Sorry for the delay.

**Comment by jasonwilliams200OK** [comment]
CC https://github.com/github/linguist/issues/2865, @jaredpar, @akoeplinger.


:+1:

**Comment by jaredpar** [comment]
CC @dustincampbell

**Comment by DustinCampbell** [comment]
FWIW, these should probably be moved over to https://github.com/OmniSharp/omnisharp-vscode and https://github.com/OmniSharp/omnisharp-roslyn
