### ISSUE TITLE
[c#] Unexpected syntax color for nested namespace declarations

### ISSUE THREAD

**Issue by aeschli** [atom/language-csharp#44]
_From @vbfox on December 1, 2015 9:12_

![2015-12-01 10_08_59-searchkey cs - rfq-hub - visual studio code](https://cloud.githubusercontent.com/assets/131878/11496639/951fcd0e-9813-11e5-8ade-7a6ba1f353e8.png)

Namespaces contained in namespace declarations don't get any syntax coloration.

_Copied from original issue: Microsoft/vscode#849_

**Comment by aeschli** [comment]
Same problem in Atom:
![image](https://cloud.githubusercontent.com/assets/6461412/11533969/acf0b19c-990c-11e5-9b9e-7122cd2c56dc.png)

**Comment by damieng** [comment]
Underlying cause was same as bug #41 now fixed.
