### ISSUE TITLE
[c#] No syntax colors in C# for usings out of namespace

### ISSUE THREAD

**Issue by aeschli** [atom/language-csharp#45]
_From @vbfox on December 1, 2015 9:8_

![2015-12-01 09_59_56-searchkey cs - rfq-hub - visual studio code](https://cloud.githubusercontent.com/assets/131878/11496467/5428b2b2-9812-11e5-8f87-30d22807d50e.png)

In the following code :

```csharp
using System.Linq;

namespace MyNamespaceIsFoo
{
    using System;
    
    public class SearchKey
    {
    }
}
```

`using System` get colored correctly but `using System.Linq` isn't.

_Copied from original issue: Microsoft/vscode#848_

**Comment by aeschli** [comment]
Same problem in Atom
![image](https://cloud.githubusercontent.com/assets/6461412/11556379/7e2d51d6-99a6-11e5-8a16-80cf6b0d8459.png)

**Comment by damieng** [comment]
Is now fixed I think through a number of commits;

![image](https://cloud.githubusercontent.com/assets/118951/18688566/dcf586ae-7f7c-11e6-826f-a9bbe92510e2.png)
