### ISSUE TITLE
[c#] wrong colorization for unsafe code pointer

### ISSUE THREAD

**Issue by aeschli** [atom/language-csharp#46]
_From @jonnyguo1988 on December 8, 2015 7:7_

![pointer](https://cloud.githubusercontent.com/assets/14086700/11649742/220b860a-9dbd-11e5-8e6d-bedd2c3a98f6.png)

hi
please see the attachment, I'm writing unsafe code in c#, but the color for the parameters of pointers is wired, I think this should be a bug.

Thank you

_Copied from original issue: Microsoft/vscode#1093_

**Comment by aeschli** [comment]
Same problem with Atom (languages-csharp 0.11.0)
![image](https://cloud.githubusercontent.com/assets/6461412/11651856/421d3ea8-9d94-11e5-8836-0dc91a5717ce.png)

**Comment by damieng** [comment]
Fixed in master, should ship in the next beta.

![image](https://cloud.githubusercontent.com/assets/118951/21558154/44ddd44a-cdea-11e6-9075-28fcb889a825.png)
