### ISSUE TITLE
C# Storage type highlighting not working for my classes 

### ISSUE THREAD

**Issue by aeschli** [atom/language-csharp#48]
_From @cdes on December 29, 2015 8:12_

I'm using the VSCode Version 0.10.6 (0.10.6).
Default dark theme.

Here's a sample code:

``` csharp
class MyClass
{

}

class Program
{
    static void Main()
    {        
        //string is highlighted
        string s = "MyClass";

        //MyClass is not highlighted
        MyClass myClass = new MyClass();
    }
}
```

Here's an image:
![screen shot 2015-12-29 at 11 13 02 am](https://cloud.githubusercontent.com/assets/1207863/12031503/c113e952-ae1d-11e5-85bf-361487e95dc9.png)

Here's a video demonstration:
https://www.youtube.com/watch?v=VpRPJc42FZQ

_Copied from original issue: Microsoft/vscode#1686_

**Comment by aeschli** [comment]
It's an issue with the csharp tokenizer, same issue in atom (languages-csharp 0.11.0)
![image](https://cloud.githubusercontent.com/assets/6461412/12174635/24a4af8c-b55e-11e5-90ed-0fcd3e8bd920.png)

**Comment by sjk07** [comment]
Any progress on this?

**Comment by 50Wliu** [comment]
@sjk07 No, not yet.  I haven't been able to take a look at fixing the C# issues, so any help would be appreciated.

**Comment by damieng** [comment]
We've done a bunch of work on master which should ship in the next atom beta that includes various improvements. Your specific code block now looks like this;

![image](https://cloud.githubusercontent.com/assets/118951/21573086/5a1ce48a-ce95-11e6-9907-a581e8f2513d.png)
