### ISSUE TITLE
C# - strings not highlighting correctly in classes

### ISSUE THREAD

**Issue by nolemon** [atom/language-csharp#52]
There's a weird glitch in highlighting strings.  If you have a string within a class and that string has a `{` anywhere in it and there's anything before the string other than `=`, ignoring `@`, then the highlighting doesn't pick up the opening `"` and starts highlighting at the end of the string instead, making the rest of the code appear to be within a string.  Here's a small example of what I mean:
![error-example](https://cloud.githubusercontent.com/assets/13686726/13572051/34e40d5e-e446-11e5-9580-bcd9af08ee6e.png)

It doesn't affect the program at all, but it gets really hard to read, especially if this happens at the top of the file.

**Comment by jamesqo** [comment]
Ran into this the other day with code that uses `string.Format`, [here's](https://github.com/dotnet/corefx/blob/b55b8085528d0199bd14fb417d3b764e643b8533/src/System.Runtime.Extensions/tests/System/Runtime/Versioning/FrameworkName.cs) an example.

I've also opened an issue at the VSCode repo about this, which uses this for the C# grammar: Microsoft/vscode#4725

**Comment by damieng** [comment]
Has been fixed in master and should ship in the next beta.  Here's a screenshot of your code from there;

![image](https://cloud.githubusercontent.com/assets/118951/21557953/0d6ef932-cde8-11e6-8150-e018eebe5e80.png)
