### ISSUE TITLE
Problems with colouring of types in items like Box<T>

### ISSUE THREAD

**Issue by Nokel81** [atom/language-csharp#57]
If the function returns a generic then the css type is "span.meta.method.return-type.cs" (even for the type in the angle brackets). I believe that the item in the angle brackets (or the angle brackets should be a different type to help with reading. 

For the parameter with footprint "SearchRequest<TransactionSearchCriteria> searchRequest" the "SearchRequest" is of type "span.variable.parameter.function.cs" but the items in the angle brackets are the same colour as the parameter name and share all the same css.

**Comment by damieng** [comment]
Generic types have been massively improved now and should ship in the next beta.   Here's a screenshot showing a VS-like theme in action;

![image](https://cloud.githubusercontent.com/assets/118951/21557928/c41387e4-cde7-11e6-9b4b-7e87fbf2349b.png)
