### ISSUE TITLE
Syntax highlighting for some new keywords

### ISSUE THREAD

**Issue by shiftkey** [atom/language-csharp#6]
So I've grabbed this screenshot which includes some syntax I think could be done better:

![screen shot 2014-02-28 at 1 53 13 pm](https://f.cloud.github.com/assets/359239/2290612/90da0154-a023-11e3-9487-05b549b10ff2.png)

In particular:
 
 - [x] `const` should be highlighted like `void`
 - [x] `async` should be highlighted like `void`
 - [ ] `Task` should be highlighted like a type
 - [ ] the `T` in `<T>` should be highlighted like a type

**Comment by ctolkien** [comment]
Here's another example, generic properties:

![example](http://i.imgur.com/O07W1Ub.png)

**Comment by lee-dohm** [comment]
It appears that you're conflating a couple things here. The language package sets the "scope" of a token. The syntax theme determines how to color those scopes.

* `const` has the scope: `.storage.modifier.source.cs`
* `void` has the scope: `.storage.type.source.cs`
* `async` has the scope: ``storage.modifier.source.cs`
* `Task` has the scope: `.meta.method.return-type.source.cs`
* `T` has the scope: `.meta.method.source.cs`

So it looks to me like `T` is the only thing that is off. The rest should probably be resolved by filing a bug on the syntax theme or just by adding some rules to your `styles.less`.

**Comment by khellang** [comment]
Syntax highlighting for `using static` is also missing;

```csharp
using static System.IO.Path;
```

**Comment by damieng** [comment]
Only remaining issue on this is generics support which is being tracked on #50
