### ISSUE TITLE
[bug] Comments not being syntax highlighted properly

### ISSUE THREAD

**Issue by jamesqo** [atom/language-csharp#62]
This line in the CoreCLR repo seems to not be highlighting properly:

https://github.com/dotnet/coreclr/blob/7b97c58/src/mscorlib/src/System/RtType.cs#L63

Not exactly sure what's causing it, but maybe it has something to do with the angle/square brackets in the comment on the previous line.

**Comment by damieng** [comment]
It's because the { on that line in the comment is causing it to think this is a new block.

**Comment by damieng** [comment]
Now fixed in master - should ship with next beta. 

![image](https://cloud.githubusercontent.com/assets/118951/21557896/6af96b9c-cde7-11e6-9a1d-f89b435b4e02.png)
