### ISSUE TITLE
Dull highlighting

### ISSUE THREAD

**Issue by Tychus** [atom/language-csharp#67]
Hi,

this is the first time i opened C# files in atom and the syntax highlighting made it impossible for me to read 90% of the code is orange/ brownish. 

checked different themes i'm on Seti / Base 16 Tomorrow dark. but it always is the same thing one color dominating the code.

is there something i should do ? is there anyway to contribute to this ?

![image](https://cloud.githubusercontent.com/assets/1427215/16759981/52d8236e-4822-11e6-89bf-8a0467fcef45.png)

**Comment by mslotema** [comment]
I agree. the syntax highlighting is not ok for C#. It looks like that the parsing of C# is not optimal.
Is there, indeed, anything we could contribute?
If so, please give us some pointers.

**Comment by lee-dohm** [comment]
Atom and all of its packages are open source. You may want to take a look at some of the topics on [Discuss, the official Atom message board](https://discuss.atom.io) about grammars and how to create or update them, specifically the [Atom FAQ](https://discuss.atom.io/c/faq) entry here:

https://discuss.atom.io/t/how-do-i-create-a-new-language-package/22461

There are other people there that have done some work on Atom grammars and should be able to help or offer pointers.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
