### ISSUE TITLE
broken coloring after formatted string

### ISSUE THREAD

**Issue by michidk** [atom/language-csharp#72]
It seems like the highlighting is broken after a formatted string:

[Example](https://github.com/michidk/BrokenEngine/blob/7df90c45174702979370b43a85fcb85576e67340/BrokenEngine/Materials/Material.cs)
As you see, everything after line 12 is blue.

might have sth todo with #43 (in my case its not a interpolated string)

**Comment by damieng** [comment]
Dupe of https://github.com/atom/language-csharp/issues/52 will track it there.
