### ISSUE TITLE
Incorrect highlighting of using statements

### ISSUE THREAD

**Issue by vorov2** [atom/language-csharp#76]
The first using statement is highlighted incorrectly.
With One Dark syntax theme:
![image](https://cloud.githubusercontent.com/assets/10725688/19783825/7393fbc4-9ca4-11e6-8c42-33a8b624c908.png)

With Atom Dark syntax theme:
![image](https://cloud.githubusercontent.com/assets/10725688/19783861/9a88342a-9ca4-11e6-90ec-c9a8648746de.png)

Doesn't work well with others too.

**Comment by damieng** [comment]
Fixed in 1.13.0
