### ISSUE TITLE
Byte-order marker breaks highlighting of first line

### ISSUE THREAD

**Issue by forivall** [atom/language-csharp#79]
I'm noticing that a lot of files that I'm opening (likely created by Visual Studio) aren't having their first line highlighted properly. Then, I finally noticed that if i place my cursor at the beginning of the file, and hit backspace, it fixes it. This revealed that there was a no-space character at the beginning of the file that was there, which I guessed was a Unicode BOM.

With BOM:
![screen shot 2016-12-02 at 6 52 40 pm](https://cloud.githubusercontent.com/assets/760204/20856323/035f847a-b8c1-11e6-80f6-28d2c6adaf9f.png)

Removed BOM:
![screen shot 2016-12-02 at 6 57 15 pm](https://cloud.githubusercontent.com/assets/760204/20856330/2c28eb6c-b8c1-11e6-9c9c-3ad5af70374d.png)

Investigation:
![screen shot 2016-12-02 at 6 55 13 pm](https://cloud.githubusercontent.com/assets/760204/20856326/0b321bc2-b8c1-11e6-85dc-97ef222c7aea.png)

This is probably a core issue, where Atom should detect utf-8 with BOM encoding (related: https://github.com/atom/atom/issues/3427).

**Comment by damieng** [comment]
Yeah, this is a core issue and affects many things - we'll close it here and track it on the bug you already linked. Thanks!
