### ISSUE TITLE
Heads up on ongoing effort in VSCode C# grammar and can we unify the two grammars?

### ISSUE THREAD

**Issue by ivanz** [atom/language-csharp#80]
Hi,

There have been some substantial improvements to the C# grammar in the VSCode repo ([here](https://github.com/ivanz/omnisharp-vscode/blob/ivan-ivan-more-syntax-improvements/syntaxes/csharp.json)) and ongoing effort to build out the test coverage ([here](https://github.com/ivanz/omnisharp-vscode/tree/ivan-ivan-more-syntax-improvements/test/syntaxes))

As such I wanted to raise your attention to this issue here: https://github.com/OmniSharp/omnisharp-vscode/issues/877 :

> Appears to me that there is some ongoing duplicated effort with the C# textmate grammar in VSCode (gitlog) and Atom (gitlog).
> 
> Seems like the only real difference between the two is JSON vs CSON, so why not extract the VSCode textmate C# grammar and test harness setup into a separate repo in OmniSharp, port any fixes from Atom and then share the same grammar across the two extensions (outping CSON, etc)?

**Comment by damieng** [comment]
I'm on the thread for the VS Code issue tracking this - we'll continue the discussion there.
