### ISSUE TITLE
Method return types with multiple generic types are not highlighted

### ISSUE THREAD

**Issue by damieng** [atom/language-csharp#88]
Sample code;

```csharp
Dictionary<String, String> DoSomething<T>() {
}
```

Current result;

![image](https://cloud.githubusercontent.com/assets/118951/21558009/9c4d61a2-cde8-11e6-86b2-b504acbb197c.png)

Expected result:

Second instance of String would be correctly highlighted.

**Comment by damieng** [comment]
Note: This is a non-trivial fix because of the way methods/functions have a highly variable signature and a lack of backtracking in the textmate based engine.

**Comment by 50Wliu** [comment]
As I commented in #51, would taking a look at how language-java implements generics help, considering how similar the two languages are?
