### ISSUE TITLE
Incorrect syntax highlighting for comments behind class definition

### ISSUE THREAD

**Issue by ssrmm** [atom/language-csharp#89]
### Prerequisites
I'm not actually using Aton, but rather found this issue through the Github syntax highlighter, [which directed me here](https://github.com/github/linguist/blob/master/vendor/README.md). As such some of the below doesn't quiet apply to my case and I've only done the points that seemed reasonable to me and removed the other ones from the list
* [X] Put an X between the brackets on this line if you have done all of the following:
    
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    

### Description

Comments are not highlighted correctly when they start behind the first line of a class definition that implements an interface.

### Steps to Reproduce
1. Copy paste this code
```csharp
public class Test : ITest // Incorrectly highlighted
{}
public class Test2 // Correctly highlighted
{}
```
2 Check syntax highlighting

**Expected behavior:**
The comment on the first line should be highlighted in grey.

**Actual behavior:** 
![grafik](https://cloud.githubusercontent.com/assets/22149188/22110973/f0043ef8-de5d-11e6-857c-06c8d583bbbb.png)

**Reproduces how often:**
Always

### Versions

Not using Atom at all (see Prequisities). Happens on Github issues.

**Comment by tomchkk** [comment]
I fixed this issue in my own implementation of the grammar by adding an `include #comments` in the `type-declaration` pattern:

**Before**:
```
      {
        begin: ":"
        end: "(?={|where)"
        patterns: [
          {
            include: "#type"
          }
          {
            match: "([\\w<>]+)\\s*"
            captures:
              "1":
                name: "storage.type.cs"
          }
        ]
      }
```
**After**:
```
      {
        begin: ":"
        end: "(?={|where)"
        patterns: [
          {
            include: "#type"
          }
          {
            match: "([\\w<>]+)\\s*"
            captures:
              "1":
                name: "storage.type.cs"
          }
          {
            include: "#comments"
          }
        ]
      }
```

I haven't got time to do my own pull request right now. Will do when I get a chance, if no one picks it up before.

**Comment by damieng** [comment]
Thanks @tomchkk - While testing your change I also noticed another place.  Comments can technically appear anywhere and that really messes up the grammar system as it's based on pattern matching using regexes rather than a traditional parser structure so we might not be able to support them everywhere - thankfully in these two cases it works just fine :)
