### ISSUE TITLE
Additional classes/parsing

### ISSUE THREAD

**Issue by PlaidPhantom** [atom/language-csharp#90]
Hi, I maintain an [Atom Theme](https://github.com/PlaidPhantom/midnight-jazz-syntax) and there's a couple things I'd like to add styling for in C#, however the parsing doesn't seem to be adding the appropriate classes.  The cases I've noticed so far are:

* parentheses on `if` statements and method definitions are not classed, though method call parens are (they get `.punctuation.definition`). Javascript classes them as `.meta.brace.round`, maybe C# could do something similar?
* Operators do not appear to get broken out at all.  In most other languages I've worked on operators will have the `.operator` class.

![image](https://cloud.githubusercontent.com/assets/678150/22181012/a4216074-e047-11e6-94bd-65b6ff1defda.png)

**Comment by 50Wliu** [comment]
We're phasing out `.meta.brace` in favor of `.punctuation.definition.whatever.(begin|end).bracket.(round|square|curly)`.  Just an FYI to whoever wants to work on this.

**Comment by damieng** [comment]
We're moving away from having too many classes as it has a large negative impact on rendering performance.
