### ISSUE TITLE
Highlighting stops working halfway through a file

### ISSUE THREAD

**Issue by chylex** [atom/language-csharp#93]
Hey, I'm coming here from [GitHub Linguist](https://github.com/github/linguist/blob/master/vendor/README.md) repository after noticing an issue with highlighting in one of my files on GitHub.

Halfway through the file, the highlighting gets a bit messed up, where some keywords and names are no longer highlighted properly. Example (everything after the highlighted line is incorrect):

![obrazek](https://cloud.githubusercontent.com/assets/3685160/24468396/615464a8-14b8-11e7-81fd-0b0c0a5abbf8.png)

and here is the [file in question](https://github.com/chylex/TweetDuck/blob/fb66beb29f4323a1878a9f424e1cd45b2d0d0e05/Core/FormBrowser.cs#L203) on my repository. Note that the file is syntactically valid and can be compiled without errors.

---

Also I noticed in another file (probably unrelated problem, let me know if I should make a separate issue for it) that extension methods are not highlighted correctly either, for example here, both 'this' and the name of the object should have a special color to be consistent with parameter highlighting elsewhere:

![obrazek](https://cloud.githubusercontent.com/assets/3685160/24468477/a654bbd4-14b8-11e7-8818-ce5093626525.png)

**Comment by michaelblyons** [comment]
This looks like a bug that disappears if you put the comment on a new line.

```cs
namespace TweetDck.Core{
    sealed partial class FormBrowser : Form{

        private void FormBrowser_ResizeEnd(object sender, EventArgs e){ // also triggers when the window moves
            if (!isLoaded)return;

            if (Location != ControlExtensions.InvisibleLocation){
                Config.BrowserWindow.Save(this);
                Config.Save();
            }
        }
    }
}
```

```cs
namespace TweetDck.Core{
    sealed partial class FormBrowser : Form{

        private void FormBrowser_ResizeEnd(object sender, EventArgs e){
            // also triggers when the window moves
            if (!isLoaded)return;

            if (Location != ControlExtensions.InvisibleLocation){
                Config.BrowserWindow.Save(this);
                Config.Save();
            }
        }
    }
}
```
