### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by fcharlie** [atom/language-csharp#94]
You have the core package "language-csharp" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (/usr/share/atom/resources/app.asar/node_modules/dalek/lib/main.js:14:14)
Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
<unknown> (/usr/share/atom/resources/app.asar/src/package-manager.js:514:32)
```

**Comment by 50Wliu** [comment]
Please read the error message.

**Comment by fcharlie** [comment]
when add a package to core packages, why not remove community package which one name

**Comment by 50Wliu** [comment]
I think that's a great question.  Would you mind opening a new issue on https://github.com/atom/dalek requesting that feature?
