### ISSUE TITLE
Failed to load a language-csharp package grammar

### ISSUE THREAD

**Issue by llllIIIIllll** [atom/language-csharp#95]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [language-csharp](https://github.com/atom/language-csharp) package 0.14.2

### Stack Trace

Failed to load a language-csharp package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\pc\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-csharp\grammars\c#.json' in C:\Users\pc\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-csharp\grammars\c#.json

Error: ENOENT: no such file or directory, open 'C:\Users\pc\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-csharp\grammars\c#.json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/language-csharp/grammars/c#.json:1:1
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by damieng** [comment]
What kind of install did you do?  AtomSetup.exe, auto-upgrader, portable...

Can you also check the 'C:\Users\pc\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-csharp\grammars\' folder to see if that file is there and if it is not whether all the directories that lead there are here.

I just checked the Atom-1.17 zip and it's definitely included there - I'm not sure how and why it wouldn't have been installed/unpacked on your machine. You could try removing Atom and reinstalling it using the 1.17 AtomSetup.exe

![image](https://cloud.githubusercontent.com/assets/118951/26140632/b30b5514-3a8c-11e7-89a1-165c276f7f1d.png)

**Comment by llllIIIIllll** [comment]
AtomSetup.exe
only build cake csx 
try to reinstall

**Comment by damieng** [comment]
Seems to be an issue with a bunch of packages, we are tracking this at https://github.com/atom/language-java/issues/94
