### ISSUE TITLE
[Bug] 'override' modifier not highlighted correctly on a property

### ISSUE THREAD

**Issue by jamesqo** [atom/language-csharp#96]
See https://github.com/jamesqo/Repository/blob/e60ba55bb17098c65ee0ab401eef4205f99b0ad8/Repository/EditFileActivity.Adapter.cs#L43 for a repro. I haven't tested, but perhaps this happens with other modifiers, e.g. `virtual`, `abstract` as well.

**Comment by damieng** [comment]
Most likely an issue with formatting around lambda syntax properties in general.
